CREATE TABLE subscriptions (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  city VARCHAR(100),
  frequency VARCHAR(20),
  confirmed BOOLEAN DEFAULT FALSE,
  token TEXT,
  subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);